/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args)  {

//        String host = "35.160.246.46";
//        int port = 3478;
//        Socket socket = new Socket(host, port);
//        InputStream input = socket.getInputStream();
//        int r = input.read();

        System.out.println("rrrrr");
        System.out.println("rrrrr");
        System.out.println("rrrrr");
        System.out.println("rrrrr");
        System.out.println("rrrrr");
        while(true){
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }

    }


}
